import Head from "next/head";
import Link from "next/link";
import MainLayout from "@/layout/MainLayout";
import { Button } from "react-bootstrap";
import Header from "@/components/Header";
import { CustomCarousel } from "@/components";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* <Header /> */}
        <CustomCarousel />
        <h1>Welcome to Next.js!</h1>
        <Link href="/news">
          <Button variant="info">Flat button</Button>
        </Link>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page: JSX.Element) {
  return <MainLayout>{page}</MainLayout>;
};
